name: docs
on: 
  push:
    branches: 
      - main
    tags: 
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install docutils pydoctor

    - name: Generate docs
      run: |
        # Run pydoctor build
        pydoctor

    - name: Push docs to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate docs"
